# Generated by Django 4.2.10 on 2024-03-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
