# Generated by Django 4.2.10 on 2024-03-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0003_alter_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='qty',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
