# Generated by Django 4.2.10 on 2024-03-17 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0004_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='receipt.store'),
        ),
    ]
