# Generated by Django 4.2.10 on 2024-03-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0005_receipt_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='branch',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
