# Generated by Django 4.2.10 on 2024-03-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0006_store_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='store',
            new_name='store_id',
        ),
    ]
